from datetime import datetime, timezone
from typing import NamedTuple

from services.db import get_connection


class PlanLimits(NamedTuple):
    monthly_limit: int   # -1 means unlimited
    max_duration_sec: int  # -1 means unlimited


PLAN_LIMITS: dict[str, PlanLimits] = {
    "free":      PlanLimits(monthly_limit=1,  max_duration_sec=15 * 60),
    "basic":     PlanLimits(monthly_limit=50, max_duration_sec=30 * 60),
    "unlimited": PlanLimits(monthly_limit=-1, max_duration_sec=-1),
}

PLAN_PRICES: dict[str, dict] = {
    "free":      {"price_yearly": 0,   "label": "Free"},
    "basic":     {"price_yearly": 10,  "label": "Basic"},
    "unlimited": {"price_yearly": 100, "label": "Unlimited"},
}


def get_monthly_usage(user_id: str) -> int:
    """Count PDFs generated by this user in the current calendar month."""
    now = datetime.now(timezone.utc)
    month_start = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0).isoformat()
    with get_connection() as conn:
        row = conn.execute(
            "SELECT COUNT(*) as cnt FROM usage WHERE user_id = ? AND created_at >= ?",
            (user_id, month_start),
        ).fetchone()
    return row["cnt"] if row else 0


def get_daily_usage(user_id: str) -> int:
    """Count PDFs generated by this user today (UTC)."""
    now = datetime.now(timezone.utc)
    day_start = now.replace(hour=0, minute=0, second=0, microsecond=0).isoformat()
    with get_connection() as conn:
        row = conn.execute(
            "SELECT COUNT(*) as cnt FROM usage WHERE user_id = ? AND created_at >= ?",
            (user_id, day_start),
        ).fetchone()
    return row["cnt"] if row else 0


def record_usage(user_id: str, job_id: str) -> None:
    now = datetime.now(timezone.utc).isoformat()
    with get_connection() as conn:
        conn.execute(
            "INSERT INTO usage (user_id, job_id, created_at) VALUES (?, ?, ?)",
            (user_id, job_id, now),
        )


def check_duration_allowed(plan: str, duration_sec: int) -> tuple[bool, str]:
    """Returns (allowed, reason). Called before queuing with video duration."""
    limits = PLAN_LIMITS.get(plan, PLAN_LIMITS["free"])
    if limits.max_duration_sec == -1:
        return True, ""
    if duration_sec > limits.max_duration_sec:
        max_min = limits.max_duration_sec // 60
        actual_min = duration_sec // 60
        if plan == "free":
            return False, (
                f"Free plan supports videos up to 15 minutes (this video is {actual_min} min). "
                "Upgrade to Basic for 30 min or Unlimited for no limit."
            )
        return False, (
            f"Basic plan supports videos up to 30 minutes (this video is {actual_min} min). "
            "Upgrade to Unlimited for no video length limit."
        )
    return True, ""


def check_can_generate(user_id: str, plan: str) -> tuple[bool, str]:
    """Returns (allowed, reason). Does NOT record usage."""
    limits = PLAN_LIMITS.get(plan, PLAN_LIMITS["free"])
    if limits.monthly_limit == -1:
        return True, ""
    if plan == "free":
        used = get_daily_usage(user_id)
        if used >= limits.monthly_limit:
            return False, (
                "Free plan allows 1 PDF per day. "
                "Upgrade to Basic ($10/year) for 50 PDFs/month or Unlimited ($100/year) for unlimited."
            )
        return True, ""
    used = get_monthly_usage(user_id)
    if used >= limits.monthly_limit:
        return False, (
            f"You've used {used}/{limits.monthly_limit} PDFs this month on the {plan.capitalize()} plan. "
            "Upgrade to Unlimited for unrestricted access."
        )
    return True, ""


def get_user_plan_info(user_id: str, plan: str) -> dict:
    limits = PLAN_LIMITS.get(plan, PLAN_LIMITS["free"])
    if plan == "free":
        used = get_daily_usage(user_id)
    else:
        used = get_monthly_usage(user_id)
    return {
        "plan": plan,
        "monthly_limit": limits.monthly_limit,
        "monthly_used": used,
    }
